### ISSUE TITLE
货郎延伸问题NPH的另一种证明方法可行性讨论

### ISSUE THREAD

**Issue by zhiyingf** [sailist/AdAlgo#10]
关于货郎延伸问题NPH证明是否可以将货郎延伸问题等价转换成货郎优化问题来证明？
就是将已知一部分货郎旅游路径上的点和与这些点相连的边都去掉，形成一个新的图G'，将已知一部分货郎旅游路径上最后一个点v作为起点，将B减去已知一部分货郎旅游路径上边长之和得到的C作为新的总行程不小于C的实数，这样就形成了一个新的TSP（优化）问题。而TSP是NPH，那么货郎延伸问题也是NPH。可以这样证明吗？

**Comment by sailist** [comment]
首先货郎延伸问题是判定问题，货郎优化问题是一个优化问题，两者不是等价转换的。

另外证明货郎延伸问题是 NPH，是通过将其他问题归约到延伸问题证明的。要么将 NPH 多项式/图灵归约到 延伸问题，要么将 NPC 问题图灵归约到 延伸问题。你的这个解法是否存在解我不太确定（可以看一下书上货郎判定问题的 NPH 证明，里面似乎用到了一个循环遍历已知路径上的点来避免某种错误，我没细看），但是用延伸问题的实例设计 TSP 实例，最多只能将 延伸问题归约到 TSP问题，证明 TSP 问题的问题复杂度，证明方向反了。

**Comment by zhiyingf** [comment]
确实，我把货郎延伸问题看成了优化问题，所以我想的是等价证明，并不是归约证明，所以应该不能说证明反了吧？不是优化问题确实不能这么做。

**Comment by sailist** [comment]
“等价”的证明本身就包括任意 A 可以转换到 B ，任意 B 可以转换到 A，需要一个可逆的函数来实现。而你这里的等价，实际上只有从 A 到 B 的说明，所以其实还是在做归约。

等价应该更像是 团问题 或者 独立集问题 的证明。

**Comment by zhiyingf** [comment]
嗯嗯。懂了。感谢！
![image](https://user-images.githubusercontent.com/38620101/103859328-d7efee80-50f4-11eb-8a8d-6cc3798cac22.png)
这句话是不是反了？

**Comment by sailist** [comment]
客气 :)

没有反，这里的图灵归约在下文用的是多项式归约，因为多项式归约也属于图灵归约。货郎判定问题可以直接被看做是货郎延伸问题（已知路径只有起点）。

当然，延伸问题也可以归约到判定问题，这一归约稍微复杂了一点，带循环，我之前没想通，就再没看。

书中有对这种类型问题的说明，可能不严谨（书中仅针对优化问题下的定义，但这俩是判定问题），但这种可以被互相归约的问题，被称为 Np-等价 的。

**Comment by zhiyingf** [comment]
嗯嗯懂了，问那个等价问题的时候我想的简单了，书本上将货郎延伸问题图灵归约到货郎判定问题的时候，就是将已知一部分货郎旅游路径上所有的点看成一个点来做的。
