### ISSUE TITLE
划分问题的一些疑问

### ISSUE THREAD

**Issue by zhiyingf** [sailist/AdAlgo#11]
![image](https://user-images.githubusercontent.com/38620101/103869523-61a7b800-5105-11eb-8015-f588fa52a13e.png)
这是否是:
![image](https://user-images.githubusercontent.com/38620101/103870118-3bcee300-5106-11eb-9777-a9daa830c3a3.png)
但是应该也不影响后文推导思路。
此外，
![image](https://user-images.githubusercontent.com/38620101/103870370-936d4e80-5106-11eb-83b4-aac5561d8814.png)
这样是否好一点：
![image](https://user-images.githubusercontent.com/38620101/103871272-d11ea700-5107-11eb-811a-e2c292a60ac1.png)

**Comment by sailist** [comment]
划分问题那我写错了，之前刚更新，你刷新一遍应该就能刷新出来。

下面这个 S(b1) 为什么是 S(A)/2 

如果是说写成 b1,b2 的形式这块的话，确实用字母直接代替取值，说明上会方便一些，不过这个问题本身很简单，我就不折腾了，你如果觉得写的清楚的话可以提一个 pr 👍

**Comment by sailist** [comment]
又看了一遍，你的最后一个元素是 2^{p-1} ，我的是 2^0 ，其实放在那个图上都一样的，只不过是第几个格子，从写起来方便的角度，或许我的更好一些（逃

**Comment by zhiyingf** [comment]
啊，那个，我左右混了，右第一个格子确实好些，不然相加就进位出去了。
