### ISSUE TITLE
关于“根据图灵归约的定义，货郎优化问题是 NP-hard，因此货郎判定问题也是 NP-hard。”的疑问？

### ISSUE THREAD

**Issue by zhiyingf** [sailist/AdAlgo#3]
![image](https://user-images.githubusercontent.com/38620101/103414023-1ea28d80-4bb7-11eb-9828-0ea8bec4ae6f.png)
在https://sailist.github.io/AdAlgo/turing/3.html中，“此时，根据图灵归约的定义，货郎优化问题是 NP-hard，因此货郎判定问题也是 NP-hard。”这句话是否是说反了呢？
![image](https://user-images.githubusercontent.com/38620101/103414104-74773580-4bb7-11eb-8c47-38e12770a668.png)

**Comment by sailist** [comment]
谢谢提醒，这一块确实写反了，这句话上面是将货郎判定归约到货郎优化，所以最后应该证明的是货郎优化的问题复杂度
