### ISSUE TITLE
关于x3c-y 公式表述优化和必要性证明的疑问

### ISSUE THREAD

**Issue by zhiyingf** [sailist/AdAlgo#4]
![image](https://user-images.githubusercontent.com/38620101/103441508-77daf180-4c89-11eb-8357-05103643430d.png)
（红线部分）
存在？
bi,1 , ... ... ,bi,6?
dj,1 , ... ... ,dj,5?
dj,1 , ... ... ,dj,3?
还有一个问题就是，x3c-y是x3c的子问题，那必要性那部分可以不证明吗？

**Comment by sailist** [comment]
是的，我本来用波浪号连接的，没有注意到波浪号在 LaTeX 里表示空格，被省略掉了... 

必要性的话，个人觉得仍然有证明的必要，因为虽然问题是子问题（只添加了交集条件限制），但是我们要证明的是这个多项式变换，或者说变换前后的两个实例的表述之间**有解条件下等价**的充要条件。

由于这个问题多项式变换的处理方式不是通过限制技术得到的，所以变换前后的两个实例不能简单的看成是包含或被包含关系，所以必要性仍然有证明的必要（禁止套娃）。

个人想法，欢迎继续讨论 :)

**Comment by zhiyingf** [comment]
嗯嗯，懂了，感谢回复！
