### ISSUE TITLE
关于X3C-Y问题的表述优化

### ISSUE THREAD

**Issue by broccoli-97** [sailist/AdAlgo#5]
![1](https://user-images.githubusercontent.com/24259908/103474216-8b4aa180-4ddc-11eb-9e2d-e42e06def165.png)

- 第一个红框部分是不是应该是 C^{\prime} \subseteq C 的关系
- 第二个红框部分加上 i \neq j 是不是更好

**Comment by sailist** [comment]
- 是的，这里可能是当初草稿写错了，打的时候没注意到
 - 是的，这里条件当初确实忽略了

**Comment by sailist** [comment]
close [fc4906](https://github.com/sailist/AdAlgo/commit/fc4906ae6dda803f1835aaa7b91d133b5b3c64b2)
