### ISSUE TITLE
图的顶点覆盖问题（VC）中的表述优化

### ISSUE THREAD

**Issue by zhiyingf** [sailist/AdAlgo#6]
![image](https://user-images.githubusercontent.com/38620101/103481859-5c522100-4e18-11eb-90c6-2452717debae.png)
这个说“每个三角形对应的边集中的三条边至少有一条边也被覆盖，因此在三角形集中必须选择边集中还未覆盖的边相连的点，最后将每个三角形集选满两个点”是否更好一点？（因为每个三角形对应的边集可能没有两个未覆盖的边，但是每个三角形要选满两个点。）

**Comment by sailist** [comment]
是的，这里表述有问题，是应该说边集来着
