### ISSUE TITLE
关于X3C 当且仅当 为何成立的疑问

### ISSUE THREAD

**Issue by SadPencil** [sailist/AdAlgo#7]
在 x3c.md 文件中存在下面一句话：
```
3DM 实例 M 中存在完美对集，当且仅当 X3C 实例 C 中存在 S 的严格覆盖。问题得证。
```

这句话的`当且仅当`为什么成立？是不是应该改为左边推出右边？

例如，如果当且仅当成立，则右边推出左边成立。
右边，对于X3C的一个实例
```
S={1,2,3,4,5,6} 
C={{1,2,3},{1,2,4},{1,2,5},{1,2,6},{4,5,6}}
```
而言，如何推出左边成立？

**Comment by sailist** [comment]
如果右边 X3C 存在严格覆盖，只需要把严格覆盖的所有元素的第一个分量放到 W，第二个分量放到 X，第三个分量放到 Y 即可

**Comment by SadPencil** [comment]
我之前举的这个例子需要根据 https://github.com/sailist/AdAlgo/issues/9 里面的解答进行排除，我举的这个例子不符合要求
