### ISSUE TITLE
X3C-Y 是否可能存在任意元素交集数量恒等于 1 的情况

### ISSUE THREAD

**Issue by YiBoWang20** [sailist/AdAlgo#8]
这里构造的实例仅是ci与cj的交集数量=0的情况，题干所给的是ci与cj的交集数量≤1，找到的这种构造方式没有问题。但若题干替换为ci与cj的交集数量=1，该如何构造对应的T和D？

**Comment by sailist** [comment]
不可能对任意元素，交集数量恒等于1。反证法，如果存在，就不可能存在严格覆盖，因为严格覆盖要求所有元素恰好出现一次。
